remote_theme: allejo/jekyll-docs-theme
name: sdSuSiE

project:
  version: 1.0.0
  download_url: https://github.com/yuanzhongshang/sdSuSiE/
  download_text: Download

license:
  software: GNU License 3.0
  software_url: https://www.gnu.org/licenses/licenses.en.html
 
links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/sdSuSiE/
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/sdSuSiE/
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/yuanzhongshang/sdSuSiE/
    - title: Issues
      icon: bug
      url: https://github.com/yuanzhongshang/sdSuSiE/issues?state=open

ui:
  mode: 'light' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#4682b4"
  border_color:
    dark: "#2A58C3"
    light: "#a2a2a3"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#4682b4"
      color2: "#FF6347"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: yuanzhongshang
    repo: sdSuSiE
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

analytics:
  google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - LICENSE.md
  - README.md
