# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglik_cpp <- function(V, betahat, shat2, prior_weight, nsex, diag_index, config_list) {
    .Call(`_sdSuSiE_loglik_cpp`, V, betahat, shat2, prior_weight, nsex, diag_index, config_list)
}

mvlmm_reg <- function(betahat, shat2, V_mat) {
    .Call(`_sdSuSiE_mvlmm_reg`, betahat, shat2, V_mat)
}

uni_reg <- function(betahat, shat2, V_mat, config_vec) {
    .Call(`_sdSuSiE_uni_reg`, betahat, shat2, V_mat, config_vec)
}

